# .github/workflows/deploy.yml
name: Deploy Google Apps Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create clasp config
        run: |
          echo '{"scriptId":"${{ secrets.SCRIPT_ID }}"}' > .clasp.json

      - name: Authenticate with clasp
        run: |
          echo '${{ secrets.CLASP_SERVICE_ACCOUNT }}' > credentials.json
          clasp login --creds credentials.json

      - name: Push code
        run: clasp push -f
