name: Deploy to Google Apps Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install
          npm install -g @google/clasp

      - name: Run ESLint
        run: npm run lint

      - name: Create clasp config files
        run: |
          echo '{"scriptId":"${{ secrets.SCRIPT_ID }}"}' > .clasp.json
          echo '{
            "token": {
              "access_token": "${{ secrets.ACCESS_TOKEN }}",
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/cloud-platform",
              "token_type": "Bearer"
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": ""${{ secrets.CLIENT_SECRET }}",",
              "redirectUri": "http://localhost"
            },
            "isLocalCreds": false
          }' > ~/.clasprc.json

      - name: Push code
        run: clasp push -f
